### ISSUE TITLE
MATCHES w/  regex w/ escapes fails to parse properly

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-pattern-matcher#39] opened 2017-08-04 23:51 UTC
if you add the line:
r"[binary_test:name MATCHES '\x61lice' ]",

NB: the r is needed, otherwise python will escape the \x61 to an a, and the parser will not see backslash 61 (which is the same as the letter a).

To the first set of ops in test_binary.py, you'll get the following:
E       ParseException: 1:26: mismatched input ''' expecting StringLiteral

A similar error is seen when passing this to the pattern validator.  If the backslashe is removed, then the pattern will be parsed properly.

**Comment by chisholm** [comment] 2017-08-22 21:42
First, `r'\x61lice'` isn't a legal string literal according to spec section 2.1.  It says:

> The escape character is the backslash ('\\' U+005c). Only the apostrophe or the backslash may follow...

You've followed a backslash with an `x`.  You'd have to use either `r'\\x61lice'` in a raw string, or `'\\\\x61lice'` in a plain string.

Also, I'm guessing you're using python 2.  Another issue is that the pattern matcher doesn't attempt to do a regex match on non-strings, and under python 2, `str` is not considered the string type, it's considered a binary type.  So that test data actually gives the name "alice" as a `str`, which is binary under python 2.  If you change it to `u"alice"`, it would actually attempt the regex match.

The tests in that file were intended to test binary data handling, so the data was mostly intended to be treated as binary (though `str` does become textual under python3).  `name_u` is deliberately string-valued to test string<->binary comparisons, which had special rules in the spec.

I think a better place to insert a string test like that is in test_basic_ops.py in the string section: `test_basic_ops_string_match()`.  I could add something like `"[test:string matches '\\\\x68ello']"`.

**Comment by jmgnc** [comment] 2017-08-24 22:41
Upon further review, it looks like that is the case.  I was thinking we avoided escapes if the following character wasn't present, but it doesn't look like it.

Re: Binary data, per the other issue, Binary data MUST be supported by MATCHES.

Even if you double the back slashes and use:
r"[binary_test:name MATCHES '\\x61lice' ]"

the test still fails:
=================================== FAILURES ===================================
__________ test_binary_match[[binary_test:name MATCHES '\\x61lice' ]] __________

So, this case still needs to be fixed...  Not sure why it isn't working properly.

And I verified that it should work fine:
>>> import pcre
>>> s = 'alice'
>>> r = r'\x61lice'
>>> pcre.match(r, s)
<pcre.Match object; span=(0, 5), match='alice'>

Only single backslash as we are post pattern escaping.

**Comment by gtback** [comment] 2017-08-29 21:39
@jmgnc: I had to update your comment since it was swallowing one of the `\`.

**Comment by gtback** [comment] 2017-08-29 21:52
@jmgnc, based on your test failure (`test_binary_match[[binary_test:name MATCHES '\\x61lice' ]]`), it looks like your pattern only has one backslash (pytest will `repr` the parameter in the test name). When I add the raw string with 2 backslashes, or a standard string with 4, the match is successful.

**Comment by gtback** [comment] 2017-08-29 21:54
I believe the current behavior is correct. If you disagree, can you explain again what the issue is?

**Comment by gtback** [comment] 2017-08-29 22:04
Oh, weird. It worked fine locally on Python 3.6, but failed on Python 2.7. We'll have to look into that.

**Comment by chisholm** [comment] 2017-08-29 23:11
As I mentioned above, `"alice"` in the test data (the value of the "name" property) is treated as binary by the pattern matcher under python2.  Until binary regex matching is implemented, that test will always fail; the pattern matcher won't even bother to attempt the regex match.  Once binary regexes are implemented, it should work.

In a sense, that test data isn't totally legit; a `json.load` on actual JSON text would produce unicode strings on python2.  Also, real binary data in an observable would be encoded into a *_bin or *_hex property, not a plain property like "name" (and JSON has no binary type).  You might notice that in other tests, there is a `u` inserted in front of string property values where I specifically wanted them to be treated as strings, and that's not the case in test_binary.  I didn't add the prefix in front of every string everywhere, I was too lazy.  I guess I should probably fix up that test data though.

**Comment by gtback** [comment] 2017-09-06 20:19
Fixed by #44

**Closed** 2017-09-06 20:20 UTC
